In [3]:
import matplotlib.pyplot as plt
plt.rcParams['font.family'] = 'Malgun Gothic'  # 한글 폰트명을 설정합니다.

ModuleNotFoundError: No module named 'matplotlib'

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import font_manager, rc
plt.rc('font', family='NanumBarunGothic')
import seaborn as sns

In [ ]:
cp_doctor = pd.read_csv("Data\보건의료기관_소재지_및_유형별__의사__간호사__약사수_20230713213342.csv", encoding='cp949')
cp_hospital = pd.read_csv("Data\의료기관_소재지_및_유형별_의료기관수_20230713212631.csv", encoding='cp949')

In [ ]:
cp_hospital = cp_hospital.set_index("행정구역별")
cp_doctor = cp_doctor.set_index("행정구역별")

In [ ]:
cp_doctor

       시군구별   유형별        병상수  의사 인력수
행정구역별
서울       소계  상급종합         소계   10372
서울       소계  종합병원    500병상이상    2224
서울       소계  종합병원  300~499병상    1524
서울       소계  종합병원  100~299병상     823
서울      종로구  상급종합         소계    1916
...     ...   ...        ...     ...
제주       소계  종합병원    500병상이상     335
제주       소계  종합병원  100~299병상     145
제주      제주시  종합병원    500병상이상     335
제주      제주시  종합병원  100~299병상     114
제주     서귀포시  종합병원  100~299병상      31

[303 rows x 4 columns]

In [ ]:
cp_hospital

       시군구별   유형별        병상수  기관수
행정구역별
서울       소계  상급종합         소계   14
서울       소계  종합병원    500병상이상    9
서울       소계  종합병원  300~499병상   11
서울       소계  종합병원  100~299병상   22
서울      종로구  상급종합         소계    2
...     ...   ...        ...  ...
제주       소계  종합병원    500병상이상    2
제주       소계  종합병원  100~299병상    5
제주      제주시  종합병원    500병상이상    2
제주      제주시  종합병원  100~299병상    4
제주     서귀포시  종합병원  100~299병상    1

[305 rows x 4 columns]

In [ ]:
# 시 열 추출
seoul_data_d = cp_doctor.loc["서울"]

gyeonggi_data_d = cp_doctor.loc['경기']

inche_data_d = cp_doctor.loc['인천']

busan_data_d = cp_doctor.loc['부산']

wusan_data_d = cp_doctor.loc['울산']

degu_data_d = cp_doctor.loc['대구']

gangju_data_d = cp_doctor.loc['광주']

dejen_data_d = cp_doctor.loc['대전']

gangwen_data_d = cp_doctor.loc['강원']

chunbuk_data_d = cp_doctor.loc['충북']

chunnam_data_d = cp_doctor.loc['충남']

jenbuk_data_d = cp_doctor.loc['전북']

jennam_data_d = cp_doctor.loc['전남']

genbuk_data_d = cp_doctor.loc['경북']

gengnam_data_d = cp_doctor.loc['경남']

jeju_data_d = cp_doctor.loc['제주']

In [ ]:
#'시군구별' 인덱스

seoul_data_d = seoul_data_d.set_index("시군구별")

gyeonggi_data_d = gyeonggi_data_d.set_index("시군구별")

inche_data_d = inche_data_d.set_index("시군구별")

busan_data_d = busan_data_d.set_index("시군구별")

wusan_data_d = wusan_data_d.set_index("시군구별")

degu_data_d = degu_data_d.set_index("시군구별")

gangju_data_d = gangju_data_d.set_index("시군구별")

dejen_data_d = dejen_data_d.set_index("시군구별")

gangwen_data_d = gangwen_data_d.set_index("시군구별")

chunbuk_data_d = chunbuk_data_d.set_index("시군구별")

chunnam_data_d = chunnam_data_d.set_index("시군구별")

jenbuk_data_d = jenbuk_data_d.set_index("시군구별")

jennam_data_d = jennam_data_d.set_index("시군구별")

genbuk_data_d = genbuk_data_d.set_index("시군구별")

gengnam_data_d = gengnam_data_d.set_index("시군구별")

jeju_data_d = jeju_data_d.set_index("시군구별")

In [ ]:
#"병상수"와 "유형" 제거

seoul_data_d = seoul_data_d.drop("병상수", axis=1)

gyeonggi_data_d = gyeonggi_data_d.drop("병상수", axis=1)

inche_data_d = inche_data_d.drop("병상수", axis=1)

busan_data_d = busan_data_d .drop("병상수", axis=1)

wusan_data_d = wusan_data_d.drop("병상수", axis=1)

degu_data_d = degu_data_d.drop("병상수", axis=1)

gangju_data_d = gangju_data_d.drop("병상수", axis=1)

dejen_data_d = dejen_data_d.drop("병상수", axis=1)

gangwen_data_d = gangwen_data_d.drop("병상수", axis=1)

chunbuk_data_d = chunbuk_data_d.drop("병상수", axis=1)

chunnam_data_d = chunnam_data_d.drop("병상수", axis=1)

jenbuk_data_d = jenbuk_data_d.drop("병상수", axis=1)

jennam_data_d = jennam_data_d.drop("병상수", axis=1)

genbuk_data_d = genbuk_data_d.drop("병상수", axis=1)

gengnam_data_d = gengnam_data_d.drop("병상수", axis=1)

jeju_data_d = jeju_data_d.drop("병상수", axis=1)

In [ ]:
# 죽이고 싶었던 "소계" 제거

seoul_data_d = seoul_data_d[~seoul_data_d.index.str.contains('소계')]

gyeonggi_data_d = gyeonggi_data_d[~gyeonggi_data_d.index.str.contains('소계')]

inche_data_d = inche_data_d[~inche_data_d.index.str.contains('소계')]

busan_data_d = busan_data_d[~busan_data_d.index.str.contains('소계')]

wusan_data_d = wusan_data_d[~wusan_data_d.index.str.contains('소계')]

degu_data_d = degu_data_d[~degu_data_d.index.str.contains('소계')]

gangju_data_d = gangju_data_d[~gangju_data_d.index.str.contains('소계')]

dejen_data_d = dejen_data_d[~dejen_data_d.index.str.contains('소계')]

gangwen_data_d = gangwen_data_d[~gangwen_data_d.index.str.contains('소계')]

chunbuk_data_d = chunbuk_data_d[~chunbuk_data_d.index.str.contains('소계')]

chunnam_data_d = chunnam_data_d[~chunnam_data_d.index.str.contains('소계')]

jenbuk_data_d = jenbuk_data_d[~jenbuk_data_d.index.str.contains('소계')]

jennam_data_d = jennam_data_d[~jennam_data_d.index.str.contains('소계')]

genbuk_data_d = genbuk_data_d[~genbuk_data_d.index.str.contains('소계')]

gengnam_data_d = gengnam_data_d[~gengnam_data_d.index.str.contains('소계')]

jeju_data_d = jeju_data_d[~jeju_data_d.index.str.contains('소계')]

In [ ]:
#"시군구별","유형별"로 합치기

seoul_data_d = seoul_data_d.groupby(["시군구별", "유형별"]).sum().reset_index()

gyeonggi_data_d = gyeonggi_data_d.groupby(["시군구별", "유형별"]).sum().reset_index()

inche_data_d = inche_data_d.groupby(["시군구별", "유형별"]).sum().reset_index()

busan_data_d = busan_data_d.groupby(["시군구별", "유형별"]).sum().reset_index()

wusan_data_d = wusan_data_d.groupby(["시군구별", "유형별"]).sum().reset_index()

degu_data_d = degu_data_d.groupby(["시군구별", "유형별"]).sum().reset_index()

gangju_data_d = gangju_data_d.groupby(["시군구별", "유형별"]).sum().reset_index()

dejen_data_d = dejen_data_d.groupby(["시군구별", "유형별"]).sum().reset_index()

gangwen_data_d = gangwen_data_d.groupby(["시군구별", "유형별"]).sum().reset_index()

chunbuk_data_d = chunbuk_data_d.groupby(["시군구별", "유형별"]).sum().reset_index()

chunnam_data_d = chunnam_data_d.groupby(["시군구별", "유형별"]).sum().reset_index()

jenbuk_data_d = jenbuk_data_d.groupby(["시군구별", "유형별"]).sum().reset_index()

jennam_data_d = jennam_data_d.groupby(["시군구별", "유형별"]).sum().reset_index()

genbuk_data_d = genbuk_data_d.groupby(["시군구별", "유형별"]).sum().reset_index()

gengnam_data_d = gengnam_data_d.groupby(["시군구별", "유형별"]).sum().reset_index()

jeju_data_d = jeju_data_d.groupby(["시군구별", "유형별"]).sum().reset_index()

In [ ]:
#없앴던 시도행별 다시 원래대로 그룹화

seoul_data_d["시군구별"] ="서울특별시"+" " + seoul_data_d["시군구별"] 

gyeonggi_data_d["시군구별"] ="경기도"+" " + gyeonggi_data_d["시군구별"] 

inche_data_d["시군구별"] ="인천광역시"+" " + inche_data_d["시군구별"] 

busan_data_d["시군구별"] ="부산광역시"+" " + busan_data_d["시군구별"] 

wusan_data_d["시군구별"] ="울산광역시"+" " + wusan_data_d["시군구별"] 

degu_data_d["시군구별"] ="대구광역시"+" " + degu_data_d["시군구별"] 

gangju_data_d["시군구별"] ="광주광역시"+ " " + gangju_data_d["시군구별"] 

dejen_data_d["시군구별"] ="대전광역시"+" " + dejen_data_d["시군구별"] 

gangwen_data_d["시군구별"] ="강원도"+" " + gangwen_data_d["시군구별"] 

chunbuk_data_d["시군구별"] ="충청북도"+" " + chunbuk_data_d["시군구별"] 

chunnam_data_d["시군구별"] ="충청남도"+" " + chunnam_data_d["시군구별"] 

jenbuk_data_d["시군구별"] ="전라북도"+" " + jenbuk_data_d["시군구별"] 

jennam_data_d["시군구별"] ="전라남도"+" " + jennam_data_d["시군구별"] 

genbuk_data_d["시군구별"] ="경상북도"+" " + genbuk_data_d["시군구별"] 

gengnam_data_d["시군구별"] ="경상남도"+ " " + gengnam_data_d["시군구별"] 

jeju_data_d["시군구별"] ="경기도"+" " + jeju_data_d["시군구별"]

In [ ]:
# 지금 까지 데이터 전원 합체
cp_doctor_a = pd.concat([seoul_data_d, gangju_data_d,inche_data_d,busan_data_d,wusan_data_d,degu_data_d,gangju_data_d
                         ,dejen_data_d,gangwen_data_d,chunbuk_data_d,chunnam_data_d,jenbuk_data_d,jennam_data_d,genbuk_data_d,gengnam_data_d
                         ,jeju_data_d])
cp_doctor_a

           시군구별   유형별  의사 인력수
0     서울특별시 강남구  상급종합    1798
1     서울특별시 강남구  종합병원     108
2     서울특별시 강동구  종합병원     711
3     서울특별시 강북구  종합병원      17
4     서울특별시 강서구  종합병원     115
..          ...   ...     ...
8   경상남도 창원시성산구  종합병원      77
9   경상남도 창원시의창구  종합병원     103
10  경상남도 창원시진해구  종합병원      18
0      경기도 서귀포시  종합병원      31
1       경기도 제주시  종합병원     449

[162 rows x 3 columns]

In [ ]:
# (종합병원 수를 새기위한)시 열 추출
seoul_data_h = cp_hospital.loc["서울"]

gyeonggi_data_h = cp_hospital.loc['경기']

inche_data_h = cp_hospital.loc['인천']

busan_data_h = cp_hospital.loc['부산']

wusan_data_h = cp_hospital.loc['울산']

degu_data_h = cp_hospital.loc['대구']

gangju_data_h = cp_hospital.loc['광주']

dejen_data_h = cp_hospital.loc['대전']

gangwen_data_h = cp_hospital.loc['강원']

chunbuk_data_h = cp_hospital.loc['충북']

chunnam_data_h = cp_hospital.loc['충남']

jenbuk_data_h = cp_hospital.loc['전북']

jennam_data_h = cp_hospital.loc['전남']

genbuk_data_h = cp_hospital.loc['경북']

gengnam_data_h = cp_hospital.loc['경남']

jeju_data_h = cp_hospital.loc['제주']

In [ ]:
#'시군구별' 인덱스

seoul_data_h = seoul_data_h.set_index("시군구별")

gyeonggi_data_h = gyeonggi_data_h.set_index("시군구별")

inche_data_h = inche_data_h.set_index("시군구별")

busan_data_h = busan_data_h.set_index("시군구별")

wusan_data_h = wusan_data_h.set_index("시군구별")

degu_data_h = degu_data_h.set_index("시군구별")

gangju_data_h = gangju_data_h.set_index("시군구별")

dejen_data_h = dejen_data_h.set_index("시군구별")

gangwen_data_h = gangwen_data_h.set_index("시군구별")

chunbuk_data_h = chunbuk_data_h.set_index("시군구별")

chunnam_data_h = chunnam_data_h.set_index("시군구별")

jenbuk_data_h = jenbuk_data_h.set_index("시군구별")

jennam_data_h = jennam_data_h.set_index("시군구별")

genbuk_data_h = genbuk_data_h.set_index("시군구별")

gengnam_data_h = gengnam_data_h.set_index("시군구별")

jeju_data_h = jeju_data_h.set_index("시군구별")

In [ ]:
#"종류별" 제거

seoul_data_h = seoul_data_h.drop("병상수", axis=1)

gyeonggi_data_h = gyeonggi_data_h.drop("병상수", axis=1)

inche_data_h = inche_data_h.drop("병상수", axis=1)

busan_data_h = busan_data_h.drop("병상수", axis=1)

wusan_data_h = wusan_data_h.drop("병상수", axis=1)

degu_data_h = degu_data_h.drop("병상수", axis=1)

gangju_data_h = gangju_data_h.drop("병상수", axis=1)

dejen_data_h = dejen_data_h.drop("병상수", axis=1)

gangwen_data_h = gangwen_data_h.drop("병상수", axis=1)

chunbuk_data_h = chunbuk_data_h.drop("병상수", axis=1)

chunnam_data_h = chunnam_data_h.drop("병상수", axis=1)

jenbuk_data_h = jenbuk_data_h.drop("병상수", axis=1)

jennam_data_h = jennam_data_h.drop("병상수", axis=1)

genbuk_data_h = genbuk_data_h.drop("병상수", axis=1)

gengnam_data_h = gengnam_data_h.drop("병상수", axis=1)

jeju_data_h = jeju_data_h.drop("병상수", axis=1)

In [ ]:
#'시군구별'로 병원수 전원 sum()사용

seoul_data_h = seoul_data_h.groupby(["시군구별", "유형별"]).sum().reset_index()

gyeonggi_data_h = gyeonggi_data_h.groupby(["시군구별", "유형별"]).sum().reset_index()

inche_data_h = inche_data_h.groupby(["시군구별", "유형별"]).sum().reset_index()

busan_data_h = busan_data_h.groupby(["시군구별", "유형별"]).sum().reset_index()

wusan_data_h = wusan_data_h.groupby(["시군구별", "유형별"]).sum().reset_index()

degu_data_h = degu_data_h.groupby(["시군구별", "유형별"]).sum().reset_index()

gangju_data_h = gangju_data_h.groupby(["시군구별", "유형별"]).sum().reset_index()

dejen_data_h = dejen_data_h.groupby(["시군구별", "유형별"]).sum().reset_index()

gangwen_data_h = gangwen_data_h.groupby(["시군구별", "유형별"]).sum().reset_index()

chunbuk_data_h = chunbuk_data_h.groupby(["시군구별", "유형별"]).sum().reset_index()

chunnam_data_h = chunnam_data_h.groupby(["시군구별", "유형별"]).sum().reset_index()

jenbuk_data_h = jenbuk_data_h.groupby(["시군구별", "유형별"]).sum().reset_index()

jennam_data_h = jennam_data_h.groupby(["시군구별", "유형별"]).sum().reset_index()

genbuk_data_h = genbuk_data_h.groupby(["시군구별", "유형별"]).sum().reset_index()

gengnam_data_h = gengnam_data_h.groupby(["시군구별", "유형별"]).sum().reset_index()

jeju_data_h = jeju_data_h.groupby(["시군구별", "유형별"]).sum().reset_index()

In [ ]:
#없앴던 시도행별 다시 원래대로 그룹화

seoul_data_h["시군구별"] ="서울특별시"+" " + seoul_data_h["시군구별"] 

gyeonggi_data_h["시군구별"] ="경기도"+" " + gyeonggi_data_h["시군구별"] 

inche_data_h["시군구별"] ="인천광역시"+" " + inche_data_h["시군구별"] 

busan_data_h["시군구별"] ="부산광역시"+" " + busan_data_h["시군구별"] 

wusan_data_h["시군구별"] ="울산광역시"+" " + wusan_data_h["시군구별"] 

degu_data_h["시군구별"] ="대구광역시"+" " + degu_data_h["시군구별"] 

gangju_data_h["시군구별"] ="광주광역시"+ " " + gangju_data_h["시군구별"] 

dejen_data_h["시군구별"] ="대전광역시"+" " + dejen_data_h["시군구별"] 

gangwen_data_h["시군구별"] ="강원도"+" " + gangwen_data_h["시군구별"] 

chunbuk_data_h["시군구별"] ="충청북도"+" " + chunbuk_data_h["시군구별"] 

chunnam_data_h["시군구별"] ="충청남도"+" " + chunnam_data_h["시군구별"] 

jenbuk_data_h["시군구별"] ="전라북도"+" " + jenbuk_data_h["시군구별"] 

jennam_data_h["시군구별"] ="전라남도"+" " + jennam_data_h["시군구별"] 

genbuk_data_h["시군구별"] ="경상북도"+" " + genbuk_data_h["시군구별"] 

gengnam_data_h["시군구별"] ="경상남도"+ " " + gengnam_data_h["시군구별"] 

jeju_data_h["시군구별"] ="경기도"+" " + jeju_data_h["시군구별"]

In [ ]:
# 지금 까지 데이터 전원 합체
cp_hospital_a = pd.concat([seoul_data_h, gangju_data_h,inche_data_h,busan_data_h,wusan_data_h,degu_data_h,gangju_data_h
                         ,dejen_data_h,gangwen_data_h,chunbuk_data_h,chunnam_data_h,jenbuk_data_h,jennam_data_h,genbuk_data_h,gengnam_data_h
                         ,jeju_data_h])
cp_hospital_a

           시군구별   유형별  기관수
0     서울특별시 강남구  상급종합    2
1     서울특별시 강남구  종합병원    2
2     서울특별시 강동구  종합병원    3
3     서울특별시 강북구  종합병원    1
4     서울특별시 강서구  종합병원    3
..          ...   ...  ...
12  경상남도 창원시의창구  종합병원    1
13  경상남도 창원시진해구  종합병원    1
0      경기도 서귀포시  종합병원    1
1        경기도 소계  종합병원    7
2       경기도 제주시  종합병원    6

[195 rows x 3 columns]

In [ ]:
cp_doctor_a = cp_doctor_a.rename(columns={"시군구별": "행정구역별"})

In [ ]:
cp_doctor_a

          행정구역별   유형별  의사 인력수
0     서울특별시 강남구  상급종합    1798
1     서울특별시 강남구  종합병원     108
2     서울특별시 강동구  종합병원     711
3     서울특별시 강북구  종합병원      17
4     서울특별시 강서구  종합병원     115
..          ...   ...     ...
8   경상남도 창원시성산구  종합병원      77
9   경상남도 창원시의창구  종합병원     103
10  경상남도 창원시진해구  종합병원      18
0      경기도 서귀포시  종합병원      31
1       경기도 제주시  종합병원     449

[162 rows x 3 columns]

In [ ]:
cp_hospital_a = cp_hospital_a.rename(columns={"시군구별": "행정구역별"})

In [ ]:
cp_hospital_a

          행정구역별   유형별  기관수
0     서울특별시 강남구  상급종합    2
1     서울특별시 강남구  종합병원    2
2     서울특별시 강동구  종합병원    3
3     서울특별시 강북구  종합병원    1
4     서울특별시 강서구  종합병원    3
..          ...   ...  ...
12  경상남도 창원시의창구  종합병원    1
13  경상남도 창원시진해구  종합병원    1
0      경기도 서귀포시  종합병원    1
1        경기도 소계  종합병원    7
2       경기도 제주시  종합병원    6

[195 rows x 3 columns]

In [ ]:
cp_doctor_a = cp_doctor_a.set_index("행정구역별")
cp_doctor_a

              유형별  의사 인력수
행정구역별
서울특별시 강남구    상급종합    1798
서울특별시 강남구    종합병원     108
서울특별시 강동구    종합병원     711
서울특별시 강북구    종합병원      17
서울특별시 강서구    종합병원     115
...           ...     ...
경상남도 창원시성산구  종합병원      77
경상남도 창원시의창구  종합병원     103
경상남도 창원시진해구  종합병원      18
경기도 서귀포시     종합병원      31
경기도 제주시      종합병원     449

[162 rows x 2 columns]

In [ ]:
cp_hospital_a = cp_hospital_a.set_index("행정구역별")
cp_hospital_a

              유형별  기관수
행정구역별
서울특별시 강남구    상급종합    2
서울특별시 강남구    종합병원    2
서울특별시 강동구    종합병원    3
서울특별시 강북구    종합병원    1
서울특별시 강서구    종합병원    3
...           ...  ...
경상남도 창원시의창구  종합병원    1
경상남도 창원시진해구  종합병원    1
경기도 서귀포시     종합병원    1
경기도 소계       종합병원    7
경기도 제주시      종합병원    6

[195 rows x 2 columns]